name: Add issues to Infrastructure Project.

on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    uses: famedly/github-workflows/.github/workflows/add-to-project.yml@github-v1
    with:
      project-url: https://github.com/orgs/famedly/projects/6
    secrets: inherit
