---
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:
  build:
    uses: famedly/github-workflows/.github/workflows/rust.yml@57b383862ba81dfa265bb33d492e2bbcbc96891d
    secrets: inherit
