---
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:
  build:
    uses: famedly/github-workflows/.github/workflows/rust.yml@sammy/dependencies
    with:
      extra_build_dependencies: 'openssl vim'
    secrets: inherit
